### ISSUE TITLE
show used time

### ISSUE THREAD

**Issue by wjx0912** [yishn/Sabaki#301] opened 2017-11-24 02:38 UTC
hi,
i use the gogui and sabaki both,  can you add 'show used time', the screenshot:
[http://image.weiqiba.com/github/question1.png](http://image.weiqiba.com/github/question1.png)

thanks

**Comment by yishn** [comment] 2017-11-24 06:12
This is a duplicate of #55. Subscribe there for updates.

**Closed by yishn** 2017-11-24 06:12 UTC
Labels: duplicate
