### ISSUE TITLE
Two-digit number labels cut-off

### ISSUE THREAD

**Issue by yewang** [yishn/Sabaki#76] opened 2016-05-03 17:49 UTC
Some wider two-digit numerical labels get cut-off slightly along their right edge. Observed this issue on the web version. Let me know if you need to a screenshot to clarify.

**Comment by yishn** [comment] 2016-05-03 18:25
Please tell me on which numbers you observed this behavior. You can paste a SGF file here directly.

**Comment by yishn** [comment] 2016-05-03 18:43
This is a duplicate of #78.

**Comment by yewang** [comment] 2016-05-03 18:47
This is what I am talking about. I'm not too sure it's a duplicate of #78

![screenshot-1](https://cloud.githubusercontent.com/assets/1282466/14994385/a84cf084-113d-11e6-9496-f0311a22cf16.png)

Even some "4"s get cut off (the extended is shortened), but it's less obvious than the curved edges getting flattened.

**Comment by yishn** [comment] 2016-05-03 18:53
I see, could you open dev tools and see at what font size they look fine to you? I can't really do much since I don't know/have the font you're using.

**Closed** 2016-05-04 18:27 UTC
Labels: bug
