### ISSUE TITLE
Problem with some texts colors in GNU/Linux

### ISSUE THREAD

**Issue by martin-damien** [yishn/Sabaki#119] opened 2016-08-13 20:37 UTC
Hi,

As you can see, we can't read some texts under GNU/Linux:

- Handicaps in the select box are black on black
- ~~Move number is black on black on the right gutter~~

![capture d ecran_2016-08-13_22-31-42](https://cloud.githubusercontent.com/assets/295478/17645420/1a5c7222-61a6-11e6-85e9-daa358dcce1d.png)
![capture d ecran_2016-08-13_22-32-23](https://cloud.githubusercontent.com/assets/295478/17645422/1d246b5e-61a6-11e6-9104-d753d2f2e4f2.png)

**Comment by yishn** [comment] 2016-08-13 22:08
I couldn't reproduce this in Ubuntu. Which distro do you use? Can you clarify what you mean by 'move number on the right gutter'? Because the move number on the slider seems to be rendered correctly in your screenshots.

**Comment by martin-damien** [comment] 2016-08-14 08:50
I'm running the latest XUbuntu.

For the gutter it is my bad.
I only have a Linux PC and I haven't look your screenshots carefully.
I excpected to see move numbers in the gutter (without the highlight) too.

I runned Sabaki with debug and I don't find what's the problem.

![capture d ecran_2016-08-14_10-47-16](https://cloud.githubusercontent.com/assets/295478/17648166/b0de89ae-620c-11e6-8326-fe9b0e246291.png)

`<option/>` are set to `#eee` but the text is black for me...

**Comment by yishn** [comment] 2016-08-14 14:39
Hm... I installed Xubuntu on my VirtualBox and it seems to be fine on there.

![Xubuntu](https://cloud.githubusercontent.com/assets/9217349/17649789/2de78ed4-623d-11e6-99fd-6daafda28813.png)

It must be something with your system. I think it's a Chrome bug/problem that I can't fix on my end, so I'm marking this as won't fix.

**Closed by yishn** 2016-08-14 14:39 UTC
Labels: more info needed
