### ISSUE TITLE
Application crash on launch

### ISSUE THREAD

**Issue by TheIronMarx** [yishn/Sabaki#70] opened 2016-04-25 01:47 UTC
Downloading and extracting the newest version for windows worked fine, but running the application throws an exception. It doesn't also properly close out the application, so I need to open the process manager and close it down before I can delete the files. Here's the error message that pops up. 

https://sli.mg/cIqAuB

I'm rocking Windows 8.1, 64bit... I don't know what else I could tell you that would help, but I'll be around to answer any questions you have and work this out.

**Comment by yishn** [comment] 2016-04-25 07:54
This seems to be caused by the update of Electron. Electron doesn't create a user data folder automatically anymore... This is now fixed and I'll upload the patch during the day. In the meantime, you can temporarily fix the problem by creating the folder `Sabaki` in `C:\Users\Sam\AppData\Roaming\`.

**Comment by yishn** [comment] 2016-04-25 08:36
This is fixed in Sabaki v0.12.2.

**Closed by yishn** 2016-04-25 08:36 UTC
Labels: bug

**Comment by TheIronMarx** [comment] 2016-04-25 14:12
You're brilliant. Cheers.
