### ISSUE TITLE
GTP console replaces spaces with commas

### ISSUE THREAD

**Issue by CamWagner** [yishn/Sabaki#235] opened 2017-05-21 02:00 UTC
I attached the Leela GTP engine to my client. When I try to adjust the time settings with the "time_settings 20 30 1" command in the GTP console, Sabaki automatically changes my command to "time_settings 20,30,1". This is the wrong syntax for Leela and results in a syntax error.

**Comment by fohristiwhirl** [comment] 2017-05-21 10:10
I believe the problem is that the Command class expects the "arguments" to be a number of parameters, whereas the parseCommand() method is sending an array.

I believe this can be fixed by making parseCommand do:

    `return new Command(id, name, ...inputs)` // Notice the added ...

**Closed** 2017-05-21 12:06 UTC
