### ISSUE TITLE
Doesn't quit on macOS

### ISSUE THREAD

**Issue by eriksvedang** [yishn/Sabaki#184] opened 2017-03-24 08:13 UTC
I'm on macOS 10.12.3 and when quitting (CMD-Q or menu) Sabaki nothing happens and the app is still running (I have to use force quit instead).

**Comment by martin-damien** [comment] 2017-03-24 08:17
Just tested too: I have the same problem under the same version of macOS and latest Sabaki release.

The application doesn't quit but is sent to the dock instead.

**Comment by yishn** [comment] 2017-03-24 09:18
This is a duplicate of #157. In the meantime, quitting the app again will quit the app.

**Closed by yishn** 2017-03-24 09:18 UTC

**Comment by apetresc** [comment] 2026-07-02 15:53
Fixed by #1035 — Sabaki now quits on the first ⌘Q on macOS instead of leaving the process running. (Tracked as a duplicate of #157.)
